### ISSUE TITLE
Importing based on URL

### ISSUE THREAD

**Issue by magthe** [lbovet/yglu#11]
I have a use case where I'd like to use `yglu`, but it relies on being able to import not only from local files, but from URLs.

A simple example would be if the import sample would still work if written like this:

```
a: !? $import('https://raw.githubusercontent.com/lbovet/yglu/master/tests/samples/imported.yaml')
b: !? .a.y
c: !? ($_.a.z)(1)
d: !? .a.y + 2
e: !? ($_.a.z)(3)
```

Is that something that would fit in `yglu` at all?

**Comment by lbovet** [comment]
I fear that adding such a support in Yglu would open the door to many more HTTP-related feature requests (authentication, certificate  handling, ...) which is way beyond the goal of the tool. The next Yglu release will enable the use of  Yglu as a library. We could add an API to provide custom functions. This way, you could write a `$get` function that fetches the dependency according to your needs. Would it fit your needs?

**Comment by magthe** [comment]
Yes, that would be perfect!

**Comment by lbovet** [comment]
Here is an example how you can define your own YAQL functions using Yglu 1.1:

```python
import sys
from yglu.expression import add_context_processor
from yglu.main import process
from yglu.cli import ErrorList

def reverse_definition(context, root):
    context["$reverse"] = lambda s: s[::-1]

add_context_processor(reverse_definition)

process(sys.stdin, sys.stdout, None, ErrorList())
```
input:
```
a: !? $reverse(hello)
```
output:
```
a: olleh
```

```
