### ISSUE TITLE
Why is there hard dependency on a specific version of ruamel.yaml?

### ISSUE THREAD

**Issue by dz0ny** [lbovet/yglu#3]
Why is there a specific version lock on ruamel.yaml==0.16.5 release? Are newer versions incompatible for some reason?

**Comment by lbovet** [comment]
I had some trauma with automatic regressions in some node packages in the past. Thus, I took the habit locking dependencies. 
Does it cause a problem because deps are shared in Python?
Would you recommend to specify an open range?

**Comment by dz0ny** [comment]
In python ruamel.yaml==0.16.5 means only use this version, so if any other dependency (in projects) requires a newer version, your library won't be installable. 
> Does it cause a problem because deps are shared in Python?
yes
> Would you recommend to specify an open range?
ruamel.yaml>=0.16.5 should be a safe choice.

**Comment by lbovet** [comment]
Thanks @dz0ny for the consulting. I open the range for both dependencies.
f6d8902a2733267f9213a47f2cd7ec5b32a8ca54
